/**
 * Emit the T2.2 migration SQL from `src/lib/question-taxonomy.ts` *and* the
 * live bank, so the controlled vocabulary has exactly one source.
 *
 *   npx tsx scripts/generate-taxonomy-migration.ts
 *
 * Why generate rather than hand-write: the backfill has to map ~70 legacy
 * free-text skill values onto 29 canonical ids, and the fold that does the
 * matching (case, punctuation, plurality) is TypeScript. Rather than
 * transliterate it into SQL or split the work across two migrations with a
 * script run manually in between — a sequencing hazard on any database that is
 * not this one — this reads the distinct legacy values out of the bank,
 * resolves each in TypeScript, and writes explicit `WHERE domain = … AND skill
 * = …` updates. The result is one self-contained migration whose every row
 * change is visible in the diff.
 *
 * Re-running it against a bank whose taxonomy is already migrated produces a
 * migration with no backfill statements, which is correct and useless — this is
 * a one-shot tool kept in the tree because the SQL it produced is unreadable
 * without it.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { TAXONOMY, resolveDomain, resolveSkill } from "../src/lib/question-taxonomy";

const prisma = new PrismaClient();

const MIGRATION = "20260808200000_taxonomy_domain_skill_tables";

/** Postgres string literal. */
function lit(value: string | null): string {
  return value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`;
}

async function main() {
  // The pre-migration columns are gone from schema.prisma, so Prisma Client no
  // longer types them. Read them raw.
  const pairs = await prisma.$queryRawUnsafe<
    { domain: string; skill: string | null; count: bigint }[]
  >(
    `SELECT "domain", "skill", COUNT(*) AS count
       FROM "Question"
      GROUP BY "domain", "skill"
      ORDER BY "domain", "skill"`,
  );

  const out: string[] = [];
  const p = (line = "") => out.push(line);

  p("-- T2.2 — replace free-text Question.domain / Question.skill with the");
  p("-- controlled vocabulary in src/lib/question-taxonomy.ts.");
  p("--");
  p("-- Generated by scripts/generate-taxonomy-migration.ts. The backfill");
  p("-- statements below were derived from the 280-question bank as it stood;");
  p("-- on an empty database they are no-ops and the DDL is all that matters.");
  p();

  // ---------- Tables ----------
  p('CREATE TABLE "Domain" (');
  p('    "id" TEXT NOT NULL,');
  p('    "name" TEXT NOT NULL,');
  p('    "sectionType" "SectionType" NOT NULL,');
  p('    "sortOrder" INTEGER NOT NULL,');
  p('    CONSTRAINT "Domain_pkey" PRIMARY KEY ("id")');
  p(");");
  p('CREATE UNIQUE INDEX "Domain_name_key" ON "Domain"("name");');
  p('CREATE INDEX "Domain_sectionType_idx" ON "Domain"("sectionType");');
  p();

  p('CREATE TABLE "Skill" (');
  p('    "id" TEXT NOT NULL,');
  p('    "domainId" TEXT NOT NULL,');
  p('    "name" TEXT NOT NULL,');
  p('    "sortOrder" INTEGER NOT NULL,');
  p('    CONSTRAINT "Skill_pkey" PRIMARY KEY ("id")');
  p(");");
  p('CREATE UNIQUE INDEX "Skill_domainId_name_key" ON "Skill"("domainId", "name");');
  p('CREATE INDEX "Skill_domainId_idx" ON "Skill"("domainId");');
  p(
    'ALTER TABLE "Skill" ADD CONSTRAINT "Skill_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
  );
  p();

  p('CREATE TABLE "TaxonomyReview" (');
  p('    "id" TEXT NOT NULL,');
  p('    "questionId" TEXT NOT NULL,');
  p('    "legacyDomain" TEXT NOT NULL,');
  p('    "legacySkill" TEXT,');
  p('    "reason" TEXT NOT NULL,');
  p('    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,');
  p('    CONSTRAINT "TaxonomyReview_pkey" PRIMARY KEY ("id")');
  p(");");
  p('CREATE UNIQUE INDEX "TaxonomyReview_questionId_key" ON "TaxonomyReview"("questionId");');
  p();

  // ---------- Seed the vocabulary ----------
  p("-- The vocabulary. Ids are the hand-written slugs from question-taxonomy.ts.");
  const domainValues = TAXONOMY.map(
    (d, i) => `  (${lit(d.id)}, ${lit(d.name)}, '${d.sectionType}', ${i})`,
  );
  p('INSERT INTO "Domain" ("id", "name", "sectionType", "sortOrder") VALUES');
  p(`${domainValues.join(",\n")};`);
  p();

  const skillValues = TAXONOMY.flatMap((d) =>
    d.skills.map((s, i) => `  (${lit(s.id)}, ${lit(d.id)}, ${lit(s.name)}, ${i})`),
  );
  p('INSERT INTO "Skill" ("id", "domainId", "name", "sortOrder") VALUES');
  p(`${skillValues.join(",\n")};`);
  p();

  // ---------- New columns ----------
  p('ALTER TABLE "Question" ADD COLUMN "domainId" TEXT;');
  p('ALTER TABLE "Question" ADD COLUMN "skillId" TEXT;');
  p();

  // ---------- Backfill ----------
  const unmappedDomains: string[] = [];
  const reviews: { domain: string; skill: string | null; reason: string; count: number }[] = [];

  p("-- Backfill. Domain first: every legacy value resolved, so this is total.");
  const domainNames = [...new Set(pairs.map((row) => row.domain))].sort();
  for (const name of domainNames) {
    const spec = resolveDomain(name);
    if (!spec) {
      unmappedDomains.push(name);
      continue;
    }
    p(
      `UPDATE "Question" SET "domainId" = ${lit(spec.id)} WHERE "domain" = ${lit(name)};`,
    );
  }
  p();

  p("-- Skills. A pair is mapped only when the resolved skill's own domain");
  p("-- matches the question's domain; the domain is authoritative, because");
  p("-- computeDomainBreakdown reads it live and re-domaining a question would");
  p("-- rewrite the score report of every historical attempt containing it.");
  let mapped = 0;
  for (const row of pairs) {
    const count = Number(row.count);
    const domainSpec = resolveDomain(row.domain);
    if (!domainSpec) continue;
    if (row.skill === null) {
      reviews.push({ ...row, count, reason: "No skill was ever assigned." });
      continue;
    }
    const skill = resolveSkill(row.skill);
    if (!skill) {
      reviews.push({
        ...row,
        count,
        reason: `"${row.skill}" has no canonical equivalent — it spans more than one skill.`,
      });
      continue;
    }
    if (skill.domainId !== domainSpec.id) {
      reviews.push({
        ...row,
        count,
        reason: `"${row.skill}" belongs to ${TAXONOMY.find((d) => d.id === skill.domainId)!.name}, but this question is filed under ${domainSpec.name}.`,
      });
      continue;
    }
    mapped += count;
    p(
      `UPDATE "Question" SET "skillId" = ${lit(skill.id)} WHERE "domain" = ${lit(row.domain)} AND "skill" = ${lit(row.skill)};`,
    );
  }
  p();

  // ---------- Review queue ----------
  p("-- Everything the mapping could not place, with its original strings kept");
  p("-- verbatim. skillId stays NULL for these.");
  for (const review of reviews) {
    const skillPredicate =
      review.skill === null ? '"skill" IS NULL' : `"skill" = ${lit(review.skill)}`;
    p('INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")');
    p(
      `SELECT md5(random()::text || "id"), "id", ${lit(review.domain)}, ${lit(review.skill)}, ${lit(review.reason)}`,
    );
    p(`  FROM "Question" WHERE "domain" = ${lit(review.domain)} AND ${skillPredicate};`);
  }
  p();

  // ---------- Enforce ----------
  p("-- Enforce. Any row still NULL here is a legacy domain the vocabulary does");
  p("-- not contain, and failing loudly beats inventing one.");
  p('ALTER TABLE "Question" ALTER COLUMN "domainId" SET NOT NULL;');
  p();
  p('DROP INDEX IF EXISTS "Question_domain_trgm_idx";');
  p('DROP INDEX IF EXISTS "Question_skill_trgm_idx";');
  p('DROP INDEX IF EXISTS "Question_domain_idx";');
  p('ALTER TABLE "Question" DROP COLUMN "domain";');
  p('ALTER TABLE "Question" DROP COLUMN "skill";');
  p();
  p('CREATE INDEX "Question_domainId_idx" ON "Question"("domainId");');
  p('CREATE INDEX "Question_skillId_idx" ON "Question"("skillId");');
  p(
    'ALTER TABLE "Question" ADD CONSTRAINT "Question_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
  );
  p(
    'ALTER TABLE "Question" ADD CONSTRAINT "Question_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE SET NULL ON UPDATE CASCADE;',
  );
  p(
    'ALTER TABLE "TaxonomyReview" ADD CONSTRAINT "TaxonomyReview_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
  );
  p();

  const dir = join(process.cwd(), "prisma", "migrations", MIGRATION);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "migration.sql"), out.join("\n"), "utf8");

  const reviewCount = reviews.reduce((sum, r) => sum + r.count, 0);
  console.log(`Wrote prisma/migrations/${MIGRATION}/migration.sql`);
  console.log(`  ${TAXONOMY.length} domains, ${skillValues.length} skills seeded`);
  console.log(`  ${mapped} questions mapped to a skill`);
  console.log(`  ${reviewCount} questions queued for review across ${reviews.length} pairs`);
  if (unmappedDomains.length) {
    console.log(`  !! unmappable domains: ${unmappedDomains.join(", ")}`);
    process.exitCode = 1;
  }

  // A human-readable copy of the queue, so the list survives outside the DB.
  const doc = [
    "# T2.2 taxonomy review queue",
    "",
    `Generated by \`scripts/generate-taxonomy-migration.ts\`. ${reviewCount} of ${pairs.reduce((s, r) => s + Number(r.count), 0)} questions could not be mapped onto the controlled vocabulary and carry \`skillId = NULL\` plus a \`TaxonomyReview\` row.`,
    "",
    "Work the queue at `/admin/questions?review=1`. Setting a skill on the question deletes its review row.",
    "",
    "| Legacy domain | Legacy skill | Questions | Why |",
    "|---|---|---|---|",
    ...reviews.map(
      (r) =>
        `| ${r.domain} | ${r.skill === null ? "_(none)_" : r.skill} | ${r.count} | ${r.reason} |`,
    ),
    "",
  ].join("\n");
  writeFileSync(join(process.cwd(), "docs", "taxonomy-review.md"), doc, "utf8");
  console.log("Wrote docs/taxonomy-review.md");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
