-- T2.2 — replace free-text Question.domain / Question.skill with the
-- controlled vocabulary in src/lib/question-taxonomy.ts.
--
-- Generated by scripts/generate-taxonomy-migration.ts. The backfill
-- statements below were derived from the 280-question bank as it stood;
-- on an empty database they are no-ops and the DDL is all that matters.

CREATE TABLE "Domain" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sectionType" "SectionType" NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    CONSTRAINT "Domain_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Domain_name_key" ON "Domain"("name");
CREATE INDEX "Domain_sectionType_idx" ON "Domain"("sectionType");

CREATE TABLE "Skill" (
    "id" TEXT NOT NULL,
    "domainId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    CONSTRAINT "Skill_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Skill_domainId_name_key" ON "Skill"("domainId", "name");
CREATE INDEX "Skill_domainId_idx" ON "Skill"("domainId");
ALTER TABLE "Skill" ADD CONSTRAINT "Skill_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "TaxonomyReview" (
    "id" TEXT NOT NULL,
    "questionId" TEXT NOT NULL,
    "legacyDomain" TEXT NOT NULL,
    "legacySkill" TEXT,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TaxonomyReview_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "TaxonomyReview_questionId_key" ON "TaxonomyReview"("questionId");

-- The vocabulary. Ids are the hand-written slugs from question-taxonomy.ts.
INSERT INTO "Domain" ("id", "name", "sectionType", "sortOrder") VALUES
  ('info-ideas', 'Information and Ideas', 'READING_WRITING', 0),
  ('craft-structure', 'Craft and Structure', 'READING_WRITING', 1),
  ('expression-ideas', 'Expression of Ideas', 'READING_WRITING', 2),
  ('standard-english', 'Standard English Conventions', 'READING_WRITING', 3),
  ('algebra', 'Algebra', 'MATH', 4),
  ('advanced-math', 'Advanced Math', 'MATH', 5),
  ('problem-solving-data-analysis', 'Problem-Solving and Data Analysis', 'MATH', 6),
  ('geometry-trigonometry', 'Geometry and Trigonometry', 'MATH', 7);

INSERT INTO "Skill" ("id", "domainId", "name", "sortOrder") VALUES
  ('info-ideas-central', 'info-ideas', 'Central Ideas and Details', 0),
  ('info-ideas-evidence', 'info-ideas', 'Command of Evidence', 1),
  ('info-ideas-inferences', 'info-ideas', 'Inferences', 2),
  ('craft-words', 'craft-structure', 'Words in Context', 0),
  ('craft-text-structure-purpose', 'craft-structure', 'Text Structure and Purpose', 1),
  ('craft-cross-text', 'craft-structure', 'Cross-Text Connections', 2),
  ('expression-synthesis', 'expression-ideas', 'Rhetorical Synthesis', 0),
  ('expression-transitions', 'expression-ideas', 'Transitions', 1),
  ('standard-boundaries', 'standard-english', 'Boundaries', 0),
  ('standard-form-structure-sense', 'standard-english', 'Form, Structure, and Sense', 1),
  ('algebra-linear-equations-one-variable', 'algebra', 'Linear equations in one variable', 0),
  ('algebra-linear-equations-two-variables', 'algebra', 'Linear equations in two variables', 1),
  ('algebra-linear-functions', 'algebra', 'Linear functions', 2),
  ('algebra-systems-two-linear-equations', 'algebra', 'Systems of two linear equations in two variables', 3),
  ('algebra-linear-inequalities', 'algebra', 'Linear inequalities in one or two variables', 4),
  ('advanced-equivalent-expressions', 'advanced-math', 'Equivalent expressions', 0),
  ('advanced-nonlinear-equations', 'advanced-math', 'Nonlinear equations in one variable and systems of equations in two variables', 1),
  ('advanced-nonlinear-functions', 'advanced-math', 'Nonlinear functions', 2),
  ('psda-ratios-rates-units', 'problem-solving-data-analysis', 'Ratios, rates, proportional relationships, and units', 0),
  ('psda-percentages', 'problem-solving-data-analysis', 'Percentages', 1),
  ('psda-one-variable-data', 'problem-solving-data-analysis', 'One-variable data: distributions and measures of center and spread', 2),
  ('psda-two-variable-data', 'problem-solving-data-analysis', 'Two-variable data: models and scatterplots', 3),
  ('psda-probability', 'problem-solving-data-analysis', 'Probability and conditional probability', 4),
  ('psda-inference', 'problem-solving-data-analysis', 'Inference from sample statistics and margin of error', 5),
  ('psda-statistical-claims', 'problem-solving-data-analysis', 'Evaluating statistical claims: observational studies and experiments', 6),
  ('geometry-area-volume', 'geometry-trigonometry', 'Area and volume', 0),
  ('geometry-lines-angles-triangles', 'geometry-trigonometry', 'Lines, angles, and triangles', 1),
  ('geometry-right-triangles-trigonometry', 'geometry-trigonometry', 'Right triangles and trigonometry', 2),
  ('geometry-circles', 'geometry-trigonometry', 'Circles', 3);

ALTER TABLE "Question" ADD COLUMN "domainId" TEXT;
ALTER TABLE "Question" ADD COLUMN "skillId" TEXT;

-- Backfill. Domain first: every legacy value resolved, so this is total.
UPDATE "Question" SET "domainId" = 'advanced-math' WHERE "domain" = 'Advanced Math';
UPDATE "Question" SET "domainId" = 'algebra' WHERE "domain" = 'Algebra';
UPDATE "Question" SET "domainId" = 'craft-structure' WHERE "domain" = 'Craft and Structure';
UPDATE "Question" SET "domainId" = 'expression-ideas' WHERE "domain" = 'Expression of Ideas';
UPDATE "Question" SET "domainId" = 'geometry-trigonometry' WHERE "domain" = 'Geometry and Trigonometry';
UPDATE "Question" SET "domainId" = 'info-ideas' WHERE "domain" = 'Information and Ideas';
UPDATE "Question" SET "domainId" = 'problem-solving-data-analysis' WHERE "domain" = 'Problem-Solving and Data Analysis';
UPDATE "Question" SET "domainId" = 'standard-english' WHERE "domain" = 'Standard English Conventions';

-- Skills. A pair is mapped only when the resolved skill's own domain
-- matches the question's domain; the domain is authoritative, because
-- computeDomainBreakdown reads it live and re-domaining a question would
-- rewrite the score report of every historical attempt containing it.
UPDATE "Question" SET "skillId" = 'advanced-equivalent-expressions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Equivalent expressions';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-functions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Evaluating functions from graphs';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-functions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Exponential functions';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-functions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Exponential models';
UPDATE "Question" SET "skillId" = 'advanced-equivalent-expressions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Interpreting nonlinear expressions';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-equations' WHERE "domain" = 'Advanced Math' AND "skill" = 'Nonlinear equations';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-equations' WHERE "domain" = 'Advanced Math' AND "skill" = 'Nonlinear equations in one variable';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-equations' WHERE "domain" = 'Advanced Math' AND "skill" = 'Nonlinear equations in one variable and systems of equations in two variables';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-equations' WHERE "domain" = 'Advanced Math' AND "skill" = 'Nonlinear equations in two variables';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-functions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Nonlinear functions';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-equations' WHERE "domain" = 'Advanced Math' AND "skill" = 'Quadratic equations';
UPDATE "Question" SET "skillId" = 'advanced-nonlinear-functions' WHERE "domain" = 'Advanced Math' AND "skill" = 'Quadratic functions';
UPDATE "Question" SET "skillId" = 'algebra-linear-functions' WHERE "domain" = 'Algebra' AND "skill" = 'Interpreting linear expressions';
UPDATE "Question" SET "skillId" = 'algebra-linear-equations-one-variable' WHERE "domain" = 'Algebra' AND "skill" = 'Isolating quantities';
UPDATE "Question" SET "skillId" = 'algebra-linear-equations-one-variable' WHERE "domain" = 'Algebra' AND "skill" = 'Linear equations in one variable';
UPDATE "Question" SET "skillId" = 'algebra-linear-equations-two-variables' WHERE "domain" = 'Algebra' AND "skill" = 'Linear equations in two variables';
UPDATE "Question" SET "skillId" = 'algebra-linear-equations-one-variable' WHERE "domain" = 'Algebra' AND "skill" = 'Linear equations with fractions';
UPDATE "Question" SET "skillId" = 'algebra-linear-functions' WHERE "domain" = 'Algebra' AND "skill" = 'Linear functions';
UPDATE "Question" SET "skillId" = 'algebra-linear-inequalities' WHERE "domain" = 'Algebra' AND "skill" = 'Linear inequalities';
UPDATE "Question" SET "skillId" = 'algebra-linear-inequalities' WHERE "domain" = 'Algebra' AND "skill" = 'Linear inequalities in one variable';
UPDATE "Question" SET "skillId" = 'algebra-linear-functions' WHERE "domain" = 'Algebra' AND "skill" = 'Linear models';
UPDATE "Question" SET "skillId" = 'algebra-systems-two-linear-equations' WHERE "domain" = 'Algebra' AND "skill" = 'Systems of linear equations';
UPDATE "Question" SET "skillId" = 'algebra-linear-inequalities' WHERE "domain" = 'Algebra' AND "skill" = 'Systems of linear inequalities';
UPDATE "Question" SET "skillId" = 'algebra-systems-two-linear-equations' WHERE "domain" = 'Algebra' AND "skill" = 'Systems of two linear equations in two variables';
UPDATE "Question" SET "skillId" = 'craft-text-structure-purpose' WHERE "domain" = 'Craft and Structure' AND "skill" = 'Text Purpose';
UPDATE "Question" SET "skillId" = 'craft-text-structure-purpose' WHERE "domain" = 'Craft and Structure' AND "skill" = 'Text Structure';
UPDATE "Question" SET "skillId" = 'craft-text-structure-purpose' WHERE "domain" = 'Craft and Structure' AND "skill" = 'Text Structure and Purpose';
UPDATE "Question" SET "skillId" = 'craft-words' WHERE "domain" = 'Craft and Structure' AND "skill" = 'Words in Context';
UPDATE "Question" SET "skillId" = 'expression-synthesis' WHERE "domain" = 'Expression of Ideas' AND "skill" = 'Rhetorical Synthesis';
UPDATE "Question" SET "skillId" = 'expression-transitions' WHERE "domain" = 'Expression of Ideas' AND "skill" = 'Transitions';
UPDATE "Question" SET "skillId" = 'geometry-area-volume' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Area';
UPDATE "Question" SET "skillId" = 'geometry-area-volume' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Area and perimeter';
UPDATE "Question" SET "skillId" = 'geometry-area-volume' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Area and volume';
UPDATE "Question" SET "skillId" = 'geometry-circles' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Circles';
UPDATE "Question" SET "skillId" = 'geometry-circles' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Circles in the coordinate plane';
UPDATE "Question" SET "skillId" = 'geometry-lines-angles-triangles' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Lines, angles, and triangles';
UPDATE "Question" SET "skillId" = 'geometry-right-triangles-trigonometry' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Right Triangles';
UPDATE "Question" SET "skillId" = 'geometry-right-triangles-trigonometry' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Right triangles';
UPDATE "Question" SET "skillId" = 'geometry-right-triangles-trigonometry' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Right triangles and trigonometry';
UPDATE "Question" SET "skillId" = 'geometry-right-triangles-trigonometry' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Triangles and trigonometric ratios';
UPDATE "Question" SET "skillId" = 'geometry-area-volume' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Volume';
UPDATE "Question" SET "skillId" = 'geometry-area-volume' WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Volume of cylinders, cones, and spheres';
UPDATE "Question" SET "skillId" = 'info-ideas-central' WHERE "domain" = 'Information and Ideas' AND "skill" = 'Central Ideas and Details';
UPDATE "Question" SET "skillId" = 'info-ideas-evidence' WHERE "domain" = 'Information and Ideas' AND "skill" = 'Command of Evidence';
UPDATE "Question" SET "skillId" = 'psda-one-variable-data' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Center, spread, and shape of distributions';
UPDATE "Question" SET "skillId" = 'psda-inference' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Data inferences';
UPDATE "Question" SET "skillId" = 'psda-inference' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Inference from sample statistics';
UPDATE "Question" SET "skillId" = 'psda-statistical-claims' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Inference from sample surveys and experiments';
UPDATE "Question" SET "skillId" = 'psda-percentages' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Percentages';
UPDATE "Question" SET "skillId" = 'psda-probability' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Probability';
UPDATE "Question" SET "skillId" = 'psda-ratios-rates-units' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Rates, ratios, and proportions';
UPDATE "Question" SET "skillId" = 'psda-ratios-rates-units' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Ratios, rates, and proportions';
UPDATE "Question" SET "skillId" = 'psda-ratios-rates-units' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Ratios, rates, proportional relationships, and units';
UPDATE "Question" SET "skillId" = 'psda-two-variable-data' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Scatterplots';
UPDATE "Question" SET "skillId" = 'psda-ratios-rates-units' WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Units and rates';
UPDATE "Question" SET "skillId" = 'standard-boundaries' WHERE "domain" = 'Standard English Conventions' AND "skill" = 'Boundaries';
UPDATE "Question" SET "skillId" = 'standard-form-structure-sense' WHERE "domain" = 'Standard English Conventions' AND "skill" = 'Form, Structure, and Sense';

-- Everything the mapping could not place, with its original strings kept
-- verbatim. skillId stays NULL for these.
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Advanced Math', 'Area and Volume', '"Area and Volume" is a Geometry and Trigonometry skill, but this question is filed under Advanced Math.'
  FROM "Question" WHERE "domain" = 'Advanced Math' AND "skill" = 'Area and Volume';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Advanced Math', 'Complex numbers', '"Complex numbers" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Advanced Math' AND "skill" = 'Complex numbers';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Advanced Math', 'Function notation', '"Function notation" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Advanced Math' AND "skill" = 'Function notation';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Advanced Math', 'Systems of two linear equations in two variables', '"Systems of two linear equations in two variables" is a Algebra skill, but this question is filed under Advanced Math.'
  FROM "Question" WHERE "domain" = 'Advanced Math' AND "skill" = 'Systems of two linear equations in two variables';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Advanced Math', NULL, 'No skill was ever assigned.'
  FROM "Question" WHERE "domain" = 'Advanced Math' AND "skill" IS NULL;
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Algebra', 'Equivalent expressions', '"Equivalent expressions" is a Advanced Math skill, but this question is filed under Algebra.'
  FROM "Question" WHERE "domain" = 'Algebra' AND "skill" = 'Equivalent expressions';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Algebra', 'Evaluating functions', '"Evaluating functions" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Algebra' AND "skill" = 'Evaluating functions';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Algebra', 'Functions', '"Functions" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Algebra' AND "skill" = 'Functions';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Algebra', NULL, 'No skill was ever assigned.'
  FROM "Question" WHERE "domain" = 'Algebra' AND "skill" IS NULL;
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Geometry and Trigonometry', 'Angles and Circles', '"Angles and Circles" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Angles and Circles';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Geometry and Trigonometry', 'Polygons', '"Polygons" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Geometry and Trigonometry' AND "skill" = 'Polygons';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Information and Ideas', 'Cross-Text Connections', '"Cross-Text Connections" is a Craft and Structure skill, but this question is filed under Information and Ideas.'
  FROM "Question" WHERE "domain" = 'Information and Ideas' AND "skill" = 'Cross-Text Connections';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Information and Ideas', 'Words in Context', '"Words in Context" is a Craft and Structure skill, but this question is filed under Information and Ideas.'
  FROM "Question" WHERE "domain" = 'Information and Ideas' AND "skill" = 'Words in Context';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Data Analysis', '"Data Analysis" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Data Analysis';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Data from tables and graphs', '"Data from tables and graphs" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Data from tables and graphs';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Data representation', '"Data representation" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Data representation';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Linear equations in one variable', '"Linear equations in one variable" is a Algebra skill, but this question is filed under Problem-Solving and Data Analysis.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Linear equations in one variable';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Linear equations in two variables', '"Linear equations in two variables" is a Algebra skill, but this question is filed under Problem-Solving and Data Analysis.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Linear equations in two variables';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Linear inequalities in one variable', '"Linear inequalities in one variable" is a Algebra skill, but this question is filed under Problem-Solving and Data Analysis.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Linear inequalities in one variable';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Linear models', '"Linear models" is a Algebra skill, but this question is filed under Problem-Solving and Data Analysis.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Linear models';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Systems of two linear equations in two variables', '"Systems of two linear equations in two variables" is a Algebra skill, but this question is filed under Problem-Solving and Data Analysis.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Systems of two linear equations in two variables';
INSERT INTO "TaxonomyReview" ("id", "questionId", "legacyDomain", "legacySkill", "reason")
SELECT md5(random()::text || "id"), "id", 'Problem-Solving and Data Analysis', 'Two-way tables', '"Two-way tables" has no canonical equivalent — it spans more than one skill.'
  FROM "Question" WHERE "domain" = 'Problem-Solving and Data Analysis' AND "skill" = 'Two-way tables';

-- Enforce. Any row still NULL here is a legacy domain the vocabulary does
-- not contain, and failing loudly beats inventing one.
ALTER TABLE "Question" ALTER COLUMN "domainId" SET NOT NULL;

DROP INDEX IF EXISTS "Question_domain_trgm_idx";
DROP INDEX IF EXISTS "Question_skill_trgm_idx";
DROP INDEX IF EXISTS "Question_domain_idx";
ALTER TABLE "Question" DROP COLUMN "domain";
ALTER TABLE "Question" DROP COLUMN "skill";

CREATE INDEX "Question_domainId_idx" ON "Question"("domainId");
CREATE INDEX "Question_skillId_idx" ON "Question"("skillId");
ALTER TABLE "Question" ADD CONSTRAINT "Question_domainId_fkey" FOREIGN KEY ("domainId") REFERENCES "Domain"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Question" ADD CONSTRAINT "Question_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TaxonomyReview" ADD CONSTRAINT "TaxonomyReview_questionId_fkey" FOREIGN KEY ("questionId") REFERENCES "Question"("id") ON DELETE CASCADE ON UPDATE CASCADE;
